import type { WorkspaceState } from "./types";

export const initialWorkspace: WorkspaceState = {
  assets: [],
  sources: [
    {
      id: "src-fab",
      kind: "FAB",
      name: "Valve FAB events",
      uri: "s3://sonar-alpha/valve/fab/date=*/*.parquet",
      grain: "wafer × step execution",
      rows: "12.8M",
      status: "ready",
      columns: ["root_lot_id", "wafer_id", "step_id", "eqp_id", "recipe_id", "tkout_time"],
    },
    {
      id: "src-et",
      kind: "ET",
      name: "Valve full-shot ET",
      uri: "s3://sonar-alpha/valve/et/date=*/*.parquet",
      grain: "wafer × item × shot × TEG",
      rows: "84.1M",
      status: "needs_mapping",
      columns: ["root_lot_id", "wafer_id", "item_id", "chip_x_pos", "chip_y_pos", "et_value"],
    },
    {
      id: "src-inline",
      kind: "INLINE",
      name: "Valve sparse INLINE",
      uri: "s3://sonar-alpha/valve/inline/date=*/*.parquet",
      grain: "selected wafer × item × position",
      rows: "1.9M",
      status: "needs_mapping",
      columns: ["root_lot_id", "wafer_id", "item_id", "measure_pos", "value"],
    },
    {
      id: "src-vm",
      kind: "VM",
      name: "Valve VM residuals",
      uri: "s3://sonar-alpha/valve/vm/date=*/*.parquet",
      grain: "wafer × step × sensor × run",
      rows: "7.4M",
      status: "ready",
      columns: ["root_lot_id", "wafer_id", "step_id", "sensor_id", "residual"],
    },
    {
      id: "src-yield",
      kind: "YIELD",
      name: "Chip yield contract",
      uri: "Not connected",
      grain: "wafer × chip",
      rows: "—",
      status: "pending",
      columns: ["chip_x", "chip_y", "pass_fail", "available_at"],
    },
    {
      id: "src-dvc",
      kind: "DVC",
      name: "Performance / DVC contract",
      uri: "Not connected",
      grain: "wafer or shot × metric",
      rows: "—",
      status: "pending",
      columns: ["metric", "value", "test_condition", "available_at"],
    },
  ],
  anchors: [
    {
      id: "anc-kelvin",
      item: "ET_KELVIN_CONT",
      family: "Kelvin",
      structure: "single MOL contact",
      unit: "ohm",
      role: "anchor",
      coverage: 92,
      confidence: "draft",
      note: "Full-shot local contact anchor. Chain decomposition candidate.",
    },
    {
      id: "anc-chain",
      item: "ET_CHAIN_METAL",
      family: "Chain",
      structure: "contact + metal line",
      unit: "ohm",
      role: "anchor",
      coverage: 88,
      confidence: "draft",
      note: "Requires contact count, line length and width topology.",
    },
    {
      id: "anc-pcca",
      item: "PC_CA_LKG",
      family: "Leakage",
      structure: "PC–CA interface",
      unit: "nA",
      role: "context",
      coverage: 76,
      confidence: "unknown",
      note: "Use log-domain common/differential index with PC–VA.",
    },
    {
      id: "anc-ocd",
      item: "OCD_TOP_CD",
      family: "OCD",
      structure: "top profile CD",
      unit: "nm",
      role: "anchor",
      coverage: 31,
      confidence: "draft",
      note: "Sparse structural anchor for ET latent and surrogate simulator.",
    },
  ],
  relations: [
    {
      id: "rel-1",
      from: "ET_KELVIN_CONT",
      to: "ET_CHAIN_METAL",
      relation: "component of chain resistance",
      evidence: "topology required",
      status: "proposed",
    },
    {
      id: "rel-2",
      from: "OCD_TOP_CD",
      to: "ET_KELVIN_CONT",
      relation: "conditional structural response",
      evidence: "shot-matched residual correlation",
      status: "proposed",
    },
  ],
  messages: [
    {
      id: "m-welcome",
      role: "assistant",
      text: "원본을 바로 wide로 펼치지 않고 S3 long-form 계약으로 등록했습니다. ET full-shot과 sparse INLINE의 anchor item, TEG topology, target grain을 대화로 정리할 수 있어요. 먼저 ET item 하나를 설명해 주세요.",
    },
  ],
};
